### ISSUE TITLE
提议：修改项目简称

### ISSUE THREAD

**Issue by Glavo** [ffip/HMCL#3]
目前 HiPer Minecraft! Launcher 使用了与 Hello Minecraft! Launcher 相同的缩写（HMCL）。

Hello Minecraft! Launcher 方希望该项目能够修改简称以示与上游的区分，降低用户混淆二者的可能性，以防造成无效反馈（到不合适的地方开 Issue） 或者难以搜索相关信息（二者信息在搜索引擎中混淆在一起）的情况发生。

我们的提议是，使用 HPMCL（**H**i**P**er **M**ine**c**raft! **L**auncher）或者 HPMC（**H**i**P**er **M**ine**c**raft! Launcher）作为简称。我们希望 HiPer Minecraft! Launcher 使用更有区分性的名称作为简称，依然以 HMCL 作为前缀(如 HMCLx)的话有不小的混淆可能性。

另外，作为建议，HiPer Minecraft! Launcher 的全名我觉得更改为 HiPer Minecraft Launcher（去掉了感叹号）比较好。`Hello Minecraft!` 是问候语，修改为 `HiPer Minecraft` 后继续使用感叹号就会很奇怪。

**Comment by yushijinhun** [comment]
I agree with @Glavo's opinion.

[HMCL](https://github.com/huanghongxun/HMCL) is licensed under [GPLv3 with additional terms](https://github.com/huanghongxun/HMCL#license), which require you to change the software name or version to **distinguish it from the original software** if you distribute a modified version of the software.

However, the author of [ffip/HMCL](https://web.archive.org/web/20221106111415/https://github.com/ffip/HMCL) still keeps the original software name "HMCL", and uses it to advertise the modified software (see [https://hmcl.mcer.cn/](https://web.archive.org/web/20221106111345/https://hmcl.mcer.cn/)). This is obviously a **violation** of HMCL's license.

I, as a copyright holder of the original software, hereby reserve the right to take legal action against this copyright violation.

**Comment by ffip** [comment]
已确定 HMCLx

**Comment by Rei-Hatada** [comment]
> 已确定 HMCLx

@ffip 反对，请使用**更有区分度**的名称。

**Comment by ffip** [comment]
> > 已确定 HMCLx
> 
> @ffip 反对，请使用**更有区分度**的名称。

嘿？再反对我就跑HMCL下面去PR分支编译，看你们还要叫啥。。。。（反对无效

**Comment by little-creeper** [comment]
> > > 已确定 HMCLx
> > 
> > 
> > @ffip 反对，请使用**更有区分度**的名称。
> 
> 嘿？再反对我就跑HMCL下面去PR分支编译，看你们还要叫啥。。。。（反对无效

人不要脸天下无敌

**Comment by shaokeyibb** [comment]
公然违反开源协议，可谓是极度的不要脸和极度的可耻

**Comment by ffip** [comment]
> > > > 已确定 HMCLx
> > > 
> > > 
> > > @ffip 反对，请使用**更有区分度**的名称。
> > 
> > 
> > 嘿？再反对我就跑HMCL下面去PR分支编译，看你们还要叫啥。。。。（反对无效
> 
> 人不要脸天下无敌

关你屁事，自己管好自己吧。我自己写的代码我爱咋的咋地。

**Comment by ffip** [comment]
> 公然违反开源协议，可谓是极度的不要脸和极度的可耻

噢？你明白这个协议的约束吗？你比我懂！

**Comment by zwx08** [comment]
作为一个普通的mc玩家，也更希望HiPer Minecraft! Launcher能改为HPMC或者HPMCL拥有更有区分度的名称，并且希望能尽早更换在几乎全文档及宣传中的HMCL标识。对于新手来说，两者皆有很可能会误导其下载到与想象中不同的HMCL，在意识到后，可能会对您的项目产生不好的印象或造成影响，甚至也有可能会对mc界产生不好的印象，此外如果您的项目后期超过了HMCL，也会造成名称不好区分的麻烦。但不管怎么说，也希望您能为minecraft及其衍生的发展做出更多的贡献

**Comment by ffip** [comment]
> 作为一个普通的mc玩家，也更希望HiPer Minecraft! Launcher能改为HPMC或者HPMCL拥有更有区分度的名称，并且希望能尽早更换在几乎全文档及宣传中的HMCL标识。对于新手来说，两者皆有很可能会误导其下载到与想象中不同的HMCL，在意识到后，可能会对您的项目产生不好的印象或造成影响，甚至也有可能会对mc界产生不好的印象，此外如果您的项目后期超过了HMCL，也会造成名称不好区分的麻烦。但不管怎么说，也希望您能为minecraft及其衍生的发展做出更多的贡献

您放心，这个项目的初衷并不是在于超过HMCL，你可以理解为更方便更新联机方面的HMCL独立发行版本，HMCLx作为下游仓库其实也可以看作是贡献测试仓库，甚至可能稳定后我们会提交主动PR到主仓库（即HMCL）。

**Comment by ffip** [comment]
该仓库的存在主要是考虑到联机方面最近变动比较大，实验性功能很多，黄鱼大佬其实不是能很及时合并仓的。于是我就叉出来了，严格意义上说，我叫HMCL都没有毛病，因为我的全称简写下来也是HMCL，你不能因为你小名 张三，我的小名就不能叫张三。

**Comment by yushijinhun** [comment]
@ffip Due to your violation of HMCL's license, I've decided to terminate your rights granted by HMCL's license.
